import { Anek_Latin } from "next/font/google";
import "./globals.css";

const font = Anek_Latin({ subsets: ["latin"] });

export const metadata = {
  title: "YCPortfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
